---
- hosts: all
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: Create the user 'mc-hetzner'
      ansible.builtin.user:
        name: mc-hetzner
        group: sudo
        comment: Minecrat Hetzner

    - name: Add 'mc_hetzner' SSH key to 'mc-hetzner'
      ansible.posix.authorized_key:
        user: mc-hetzner
        key: "{{ lookup('file', '~/.ssh/mc_hetzner.pub') }}"
        state: present
  roles:
    - geerlingguy.security
    - geerlingguy.pip
    - geerlingguy.docker
